###############################################################################
#        _       _             _   _            _____  _
#       | |     | |           | | | |          |  __ \(_)
#       | | ___ | |__  _ __   | |_| |__   ___  | |__) |_ _ __  _ __   ___ _ __
#   _   | |/ _ \| '_ \| '_ \  | __| '_ \ / _ \ |  _  /| | '_ \| '_ \ / _ \ '__|
#  | |__| | (_) | | | | | | | | |_| | | |  __/ | | \ \| | |_) | |_) |  __/ |
#   \____/ \___/|_| |_|_| |_|  \__|_| |_|\___| |_|  \_\_| .__/| .__/ \___|_|
#                                                       | |   | |
#                                                       |_|   |_|
#
# Copyright (c) 2023-2024 Claudio André <dev at claudioandre.slmail.me>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
###############################################################################
# Cirrus CI configuration
# More info at https://github.com/openwall/john-packages

---
macOS_task:
  name: macOS M2
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest

  env:
    CIRRUS_CLONE_DEPTH: "10"
    BUILD_OPS: "--build=aarch64-apple-darwin --enable-werror"
    CC: "clang"
    MAKE_FLAGS: "-sj4"
    TARGET_ARCH: "macOS ARM"
    EXTRA: "full;extra"
    TEST: "macOS;"
    BASE: "Apple macOS M2"
    DEPLOY_PAK: "Yes"
    RELEASE_COMMIT: "f9fedd238b0b1d69181c1fef033b85c787e96e57"

  info_script: |
    git clone --depth 10 https://github.com/openwall/john.git ~/tmp
    cp -r ~/tmp/. .

    wget https://raw.githubusercontent.com/openwall/john-packages/main/scripts/ci_controller.sh \
      -O .ci/ci_controller.sh
    chmod +x .ci/ci_controller.sh
    .ci/ci_controller.sh "$TARGET_ARCH" INFO
    echo  "$CIRRUS_TASK_ID" > Build._ID

  build_script: |
    .ci/ci_controller.sh "$TARGET_ARCH" BUILD

    # Format crash on ARM
    echo '[Local:Disabled:Formats]' >> run/john-local.conf
    echo 'SunMD5 = Y' >> run/john-local.conf
    .ci/ci_controller.sh "$TARGET_ARCH" TEST

  package_script: |
    wget https://raw.githubusercontent.com/openwall/john-packages/main/scripts/clean_package.sh \
      -O .ci/clean_package.sh
    source .ci/clean_package.sh

    7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=128m -ms=on JtR-macArm.7z ./
    7z a -tzip -mx=9 JtR-macArm.zip ./
    sha256sum -- JtR-macArm.*

  always:
    binaries_artifacts:
      path: "JtR-macArm.*"

    id_artifacts:
      path: "Build._ID"
